services:

  mysql:
    image: mysql:latest
    restart: always
    ports:
        - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'honkboard_local'
      MYSQL_USER: 'honkboard'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"
    networks:
      - honkboard_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  go:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /honkboard
    ports:
      - "4000:4000"
    volumes:
      - .:/honkboard
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - honkboard_network

networks:
    honkboard_network:
        driver: bridge
volumes:
    honkboard-mysql:
        driver: local
